### ISSUE TITLE
User story 6: As a user, I want to be able to reset my password if I forgot it

### ISSUE THREAD

**Issue by JoComp27** [JoComp27/SOEN341-SA1#71]
Story points : 6 
Risk: High
Priority: Medium

Description : 
Set up an email system in which a user could receive an email if they ever forgot their password on this site.

PS : This might be implemented in Sprint 4 instead.

**Comment by TiraFire** [comment]
Acceptance Test
-------------------------
Need: Link on sign in page
Added: Link to go to another php page
Comments: Simple task, does not need anything more
--------------------------
Need: Enter username or email
Added: Input area to provide email or username.
Comments: Checks the input against the sql tables and checks if it exists
---------------------------------
Need: Ability to change the password
Added: Input area for the new password
Comments: Tests if they are the same given, changes it in the backend. 
--------------------------------
Need: Security to prevent others from changing my password
Added: ... Will add verification for birthday
Comments: Could not use email since it either costs money or not compatible with our setup (Possibly with twilio or aws in the next sprint)

------------
In all, it allows one to change their password if they forgot but needs more security!

**Comment by TiraFire** [comment]
![image](https://user-images.githubusercontent.com/25015601/37223881-e3689ad0-239f-11e8-8015-fad867d1d2e0.png)
